export * from './auth/auth.component';
export * from './card-list/card-list.component';
export * from './dashboard/dashboard.component';
export * from './doctor-list/doctor-list.component';
export * from './home/home.component';
export * from './error404/error404.component'
export * from './footer/footer.component';
export * from './header/header.component';
export * from './home/home.component';
export * from './private-cabinet/private-cabinet.component';
export * from './reg/reg.component';
export * from './side-bar/side-bar.component';
export * from './timetable/timetable.component';
